name: Create a GitHub Release

inputs:
  token:
    description: GitHub token for creating GitHub Releases.
    required: true

runs:
  using: "composite"
  steps:
    - uses: taiki-e/checkout-action@v1
    - name: Install Rust
      run: rustup update stable --no-self-update
      shell: bash --noprofile --norc -CeEuxo pipefail {0}
    - run: cargo package
      shell: bash --noprofile --norc -CeEuxo pipefail {0}
    - uses: taiki-e/create-gh-release-action@v1
      with:
        changelog: CHANGELOG.md
        title: Release $version
        branch: main
        token: ${{ inputs.token }}
