name: Create a GitHub Release

inputs:
  token:
    description: GitHub token for creating GitHub Releases.
    required: true
  package-options:
    description: Extra options to pass to `cargo package`.
    required: false
    type: string
    default:

runs:
  using: composite
  steps:
    - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
    - name: Install Rust
      run: rustup update stable --no-self-update
      shell: bash
    - run: cargo package ${INPUTS_PACKAGE_OPTIONS}
      shell: bash
      env:
        INPUTS_PACKAGE_OPTIONS: ${{ inputs.package-options }}
    - uses: taiki-e/create-gh-release-action@eba8ea96c86cca8a37f1b56e94b4d13301fba651 # v1.11.0
      with:
        changelog: CHANGELOG.md
        title: Release $version
        token: ${{ inputs.token }}
