name: Create a GitHub Release

inputs:
  token:
    description: GitHub token for creating GitHub Releases.
    required: true
  package-options:
    description: Extra options to pass to `cargo package`.
    required: false
    type: string
    default:

runs:
  using: composite
  steps:
    - uses: taiki-e/checkout-action@v1
    - name: Install Rust
      run: rustup update stable --no-self-update
      shell: bash
    - run: cargo package ${{ inputs.package-options }}
      shell: bash
    - uses: taiki-e/create-gh-release-action@v1
      with:
        changelog: CHANGELOG.md
        title: Release $version
        token: ${{ inputs.token }}
