name: Create release artifacts
description: Create release artifacts, e.g. binary packages, and upload them to a GitHub Release.

inputs:
  binary:
    description: Name of the binary to upload. Defaults to the repository name.
    required: false
  target:
    description: Target triple, e.g. aarch64-apple-darwin
    required: true
  token:
    description: GitHub token for creating GitHub Releases.
    required: true

runs:
  using: composite
  steps:
    - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
    - name: Install Rust
      run: rustup update stable --no-self-update
      shell: bash
    - uses: taiki-e/setup-cross-toolchain-action@3d9770ce98eb7dbcf378563182a5e8031165f75b # v1.41.0
      with:
        target: ${{ inputs.target }}
        runner: none
    - run: | # zizmor: ignore[github-env] random heredoc to prevent injection
        EOF=END-$(openssl rand -hex 8)
        echo "RUSTFLAGS<<${EOF}" >> "${GITHUB_ENV}"
        echo "${RUSTFLAGS} -C target-feature=+crt-static" >> "${GITHUB_ENV}"
        echo "END-${EOF}" >> "${GITHUB_ENV}"
      shell: bash
      if: contains(inputs.target, '-windows-msvc')
    - run: | # zizmor: ignore[github-env] random heredoc to prevent injection
        EOF=END-$(openssl rand -hex 8)
        echo "RUSTFLAGS<<${EOF}" >> "${GITHUB_ENV}"
        echo "${RUSTFLAGS} -C target-feature=+crt-static -C link-self-contained=yes" >> "${GITHUB_ENV}"
        echo "END-${EOF}" >> "${GITHUB_ENV}"      shell: bash
      shell: bash
      if: contains(inputs.target, '-linux-musl')
    # https://doc.rust-lang.org/rustc/platform-support.html
    - run: | # zizmor: ignore[github-env] static string
        printf 'MACOSX_DEPLOYMENT_TARGET=10.12\n' >>"${GITHUB_ENV}"
      shell: bash
      if: inputs.target == 'x86_64-apple-darwin'
    - run: | # zizmor: ignore[github-env] static string
        printf 'MACOSX_DEPLOYMENT_TARGET=11.0\n' >>"${GITHUB_ENV}"
      shell: bash
      if: inputs.target == 'aarch64-apple-darwin' || inputs.target == 'universal-apple-darwin'
    - uses: taiki-e/upload-rust-binary-action@f0d45ae91ee7b8ee928de7a9d04d893a08bcbec6 # v1.30.2
      with:
        bin: ${{ inputs.binary || github.event.repository.name }}
        target: ${{ inputs.target }}
        tar: all
        zip: windows
        token: ${{ inputs.token }}
