name: weekly-update

on:
  schedule:
    - cron: "0 12 * * 5" # Every Friday at 12:00 UTC (5am PDT / 4am PST).
  workflow_dispatch:

# Writes to PRs and workflows are done with secrets.WORKFLOW_UPDATE_TOKEN.
permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # zizmor: ignore[artipacked] no archive; needed for git
          persist-credentials: true
          token: ${{ secrets.WORKFLOW_UPDATE_TOKEN }}
      - uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          update: true
          skip_push: true
          github_token: ${{ secrets.WORKFLOW_UPDATE_TOKEN }}
      - name: Open PR if changed
        run: |
          set -euo pipefail

          if [[ -z $(git status --porcelain) ]]; then
            exit 0
          fi

          MESSAGE='Weekly dependency update.'
          BRANCH="weekly-update"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add -A
          git commit -m "$MESSAGE"
          git push -u origin "$BRANCH" --force

          if ! gh pr list --head "$BRANCH" --state open --json number --jq '.[0]' | grep -q .; then
            gh pr create \
              --title "$MESSAGE" \
              --body 'Automated weekly update.'
          fi
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_UPDATE_TOKEN }}
